config/routes.rb
FrameItIn::Application.routes.draw do
  get "public/:id" =>"public#index", as: :public
  get "show/:id" =>"public#show", as: :show

  resources :pictures, except: [:show, :new]
  get "pictures/:id" =>"pictures#index", as: :myuploads

  devise_for :users

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  attr_accessible :image_data, :name, :public, :user
  validates_format_of :name, with: /^[a-z\s_0-9]+$/i, on: :create, on: :update

  default_scope order: 'created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!
  # GET /pictures
  # GET /pictures.json
  def index
    id = (params[:id].to_i || 0) * 8
    @pictures = current_user.pictures.limit(8).offset(id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1/edit
  def edit
    session[:ref]= request.referrer
    @picture = current_user.pictures.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = current_user.pictures.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    # ref = request.referrer
    @picture = current_user.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to session[:ref] , notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = current_user.pictures.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
 def index
    id = (params[:id].to_i || 0) * 8
    @pictures = Picture.where(public: true).limit(8).offset(id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  def show
    @picture = Picture.find_by_id_and_public(params[:id], true)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
   <!--[if IE]><meta  http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FrameItIn" %></title>
    <%= csrf_meta_tags %>
    <!--Easel and Create libraries-->
    <!--
    <script src="http://code.createjs.com/easeljs-0.7.1.min.js"></script>
    <script src="http://code.createjs.com/createjs-2013.12.12.min.js"></script>
    -->
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <a  href = "#" id = "cameraButton" class="glyphicon glyphicon-camera notvisible btn btn-primary"></a>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'FrameInIt', root_path, class: "navbar_brand glyphicon" %></li>
            <li><%= link_to "Public pics", public_path(0), class: "glyphicon glyphicon-globe" %></li>
            <% if !current_user %>
              <li class="dropdown glyphicon">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Themes <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#" data-theme="default" class="theme-link">Default</a></li>
                <li><a href="#" data-theme="amelia" class="theme-link">Amelia</a></li>
                <li><a href="#" data-theme="cerulean" class="theme-link">Cerulean</a></li>
                <li><a href="#" data-theme="cosmo" class="theme-link">Cosmo</a></li>
                <li><a href="#" data-theme="cyborg" class="theme-link">Cyborg</a></li>
                <li><a href="#" data-theme="flatly" class="theme-link">Flatly</a></li>
                <li><a href="#" data-theme="journal" class="theme-link">Journal</a></li>
                <li><a href="#" data-theme="readable" class="theme-link">Readable</a></li>
                <li><a href="#" data-theme="simplex" class="theme-link">Simplex</a></li>
                <li><a href="#" data-theme="slate" class="theme-link">Slate</a></li>
                <li><a href="#" data-theme="superhero" class="theme-link">SuperHero</a></li>
                <li><a href="#" data-theme="spacelab" class="theme-link">Spacelab</a></li>
                <li><a href="#" data-theme="united" class="theme-link">United</a></li>
              </ul>
            </li>
              <li><%= link_to 'Sign In', new_user_session_path, class: "glyphicon" %></li>
            <% else %>
              <li id="user"><%= link_to "My pics", myuploads_path(0), class: "glyphicon glyphicon-cloud" %></li>
              <li class="dropdown glyphicon">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Themes <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#" data-theme="default" class="theme-link">Default</a></li>
                <li><a href="#" data-theme="amelia" class="theme-link">Amelia</a></li>
                <li><a href="#" data-theme="cerulean" class="theme-link">Cerulean</a></li>
                <li><a href="#" data-theme="cosmo" class="theme-link">Cosmo</a></li>
                <li><a href="#" data-theme="cyborg" class="theme-link">Cyborg</a></li>
                <li><a href="#" data-theme="flatly" class="theme-link">Flatly</a></li>
                <li><a href="#" data-theme="journal" class="theme-link">Journal</a></li>
                <li><a href="#" data-theme="readable" class="theme-link">Readable</a></li>
                <li><a href="#" data-theme="simplex" class="theme-link">Simplex</a></li>
                <li><a href="#" data-theme="slate" class="theme-link">Slate</a></li>
                <li><a href="#" data-theme="superhero" class="theme-link">SuperHero</a></li>
                <li><a href="#" data-theme="spacelab" class="theme-link">Spacelab</a></li>
                <li><a href="#" data-theme="united" class="theme-link">United</a></li>
              </ul>
            </li>
              <li><%= link_to current_user.email, edit_user_registration_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "glyphicon" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      <div id = "fileNameDiv"></div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Alert:</strong> 
            <%= alert %>
          </div>
          <% end %>
          <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Notice:</strong> 
            <%= notice %>
          </div>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

      <footer>
        <p>&copy; FrameItIn 2014</p>
      </footer>

  </body>
</html>

app/views/pictures/_form.html.erb
<div class="login center-block">
<%= form_for(@picture, html:{role:"form", class: "form-horizontal"}) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">   
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <!-- <div class="field">
    <%#= f.label :image_data %><br />
    <%#= f.text_area :image_data %>
  </div> -->
  <div class="form-group">
    <%= f.label :public, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :public, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/pictures/edit.html.erb
<div class="login center-block">
<h1>Editing picture</h1>

<%= form_for(@picture, html:{role:"form", class: "form-horizontal"}) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :created_at, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">   
    <%= f.text_field :created_at, class: "form-control", disabled:"true" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">   
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :public, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :public, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save", class: "btn btn-success" %>
      <%=link_to "Download", @picture.image_data, download: @picture.name , class: "btn btn-success"%>
      <%= link_to 'Cancel', request.referer, class: "btn btn-success" %>
			<%= link_to 'Delete', picture_path(params[:id]), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
<% end %>
</div>

app/views/pictures/index.html.erb
<div data-ng-app="myApp">
	<a id="scrollLeft" data-ng-href="/pictures/{{($scope.id>1)?$scope.id-1:0}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span></a>
	<a id="scrollRight" data-ng-href="/pictures/{{$scope.id+1}}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-right"></span></a>
	<div data-ng-controller="UploadController" id="pics">
  	<div class="reveal-animation uploadedPics" data-ng-repeat="pic in pictures">
  		<a data-ng-href="/pictures/{{pic.id}}/edit"> 
  			<img data-ng-src="{{pic.image_data}}"/></a>
  	</div>     
  </div>
</div>

app/views/welcome/index.html.erb
<article>
  <section id="splash">
    <p id="errorMessage">Loading...</p>
  </section>
  <section id="app" hidden>
    <div class="row">
      <!--left hand strip of photos - becomes full width for small devices-->
      <div class="col-xs-12 col-sm-4 col-lg-3">
        <div id = "snapshots" class = "snapshots"></div> 
      </div>

      <!--camera and edit picture are side by side for large displays, then become one
      above the other for medium and small displays -->
      <!--Camera area-->
      <div class="col-xs-12 col-sm-8 col-lg-4">
        <h3 class="description">Camera</h3>
        <p class ="description">Just click the 'shoot' button to start taking pictures. Your snapshots will be displayed on the left. You can save or upload directly from there, or you can edit a picture first by clicking 'select'.</p>
        <p><video id="monitor" autoplay></video>
        <p><input type="button"  id = "shootButton" value="Shoot" class="btn btn-primary">
      </div> 

      <!--Editing Area-->
      <div id = "editarea" class="col-xs-12 col-sm-8 col-lg-5"> 
        <h3 class="description">Editing Area</h3>
          <p class ="description">Change the colour and brightness, or add a border. Save or upload picture from here when you are done. </p>  
        <div id="dropArea" class="center-block">          
          <p>            
            <a href="#" id="convertgrey" class="btn btn-primary" role="button">Grey</a>
            <a href="#" id="convertsepia" class="btn btn-primary" role="button">Sepia</a>
            <a href="#" id="brighten" class="btn btn-primary" role="button">Bright</a>
            <a href="#" id="darken" class="btn btn-primary" role="button">Dark</a>
            <a href="#" id='fullscreen' class="btn btn-primary" role="button">View</a>
          </p>
          <p><canvas id="dropPic" width="400" height="300"></canvas></p>
          <p> 
            <a href="#" id="drawblackborder" class="btn btn-primary" role="button">Black Border</a>
            <a href="#" id="drawwhiteborder" class="btn btn-primary" role="button">White Border</a>      
            <a href="#" id="returncolour" class="btn btn-primary" role="button">Undo All</a>
          </p>
          <p>          
            <a href="#" id='link' class="btn btn-primary" role="button">Save</a>
            <a href="#" id='upload' class="btn btn-primary" role="button">Upload</a>
          </p>
        </div><!--end droparea div-->
      </div><!--end col div-->
      
    </div><!--end row div-->
  </section>
</article>
<script>
$('#snapshots').slimScroll({
    width: 'px',
    height: '700px',
    size: '12px',
    railVisible: true,
    alwaysVisible: true,
    railColor: '#e51400',
    color: '#000000',
    railOpacity: 0.5
  });
</script>